spring.data.mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DATABASE:votesapp}
    authenticationDatabase: ${MONGO_AUTH_DB:}
    username: ${MONGO_USERNAME:}
    password: ${MONGO_PASSWORD:}