# Somehow just logging.level ist not working in .yml,
# in .properties it is. I'll create an issue for this
logging:
    level: 
        org: ${LOGGING_LEVEL:INFO}
        net: ${LOGGING_LEVEL:INFO}
        com: ${LOGGING_LEVEL:INFO}
        de: ${LOGGING_LEVEL:INFO}